# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Build and Push Docker Image GitHub Action: https://github.com/marketplace/actions/build-and-push-docker-images

name: Java CI with Gradle New

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java-am:
    runs-on: [ ubuntu-latest ]  # This is to just run on ubuntu    
    # environment: DEV
    # Below is to run on all three
    # runs-on: ${{matrix.os}}
    # strategy: 
    #   matrix:
    #     os: [ ubuntu-latest,windows-latest,macOS-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # - name: Build and push my image
    #     uses: docker/build-push-action@v3
    #     with:
    #       push: true
    #       # tags: user/app:latest 

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Login to DockerHub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:latest

    # https://github.com/mr-smithers-excellent/docker-build-push
    # - name: Build and Push Docker Image 
    #   uses: mr-smithers-excellent/docker-build-push@v5  
    #   with:
    #     image: 452112/amdockerrepo
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
        
      # https://github.com/marketplace/actions/build-and-push-docker-images  
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}        
